import {
  KategoriKas,
  Transaksi,
  Fasilitas,
  Reservasi,
  Mustahiq,
  HewanQurban,
  Pegawai,
  Absensi,
  SlipGaji,
  ZakatFitrahTrx,
  User,
  Warga,
  ProfilLembaga,
  PengurusLembaga,
  RekeningLembaga,
  Kegiatan,
  InventoryItem,
} from '@/types/dkm';

export const INITIAL_USERS: User[] = [
  { id: 1, nama: 'H. Ahmad Dahlan (Ketua DKM)', email: 'ketua@almuhajirin.org', role: 'KETUA_DKM' },
  { id: 2, nama: 'Ustadz Ridwan, S.E (Bendahara)', email: 'bendahara@almuhajirin.org', role: 'BENDAHARA' },
  { id: 3, nama: 'Fian Tampan (Petugas Piket)', email: 'piket@almuhajirin.org', role: 'PIKET' },
  { id: 4, nama: 'Admin IT DKM', email: 'admin@almuhajirin.org', role: 'SUPER_ADMIN' },
];

export const INITIAL_KATEGORI_KAS: KategoriKas[] = [
  { id: 1, nama: 'Kas Operasional & Kebersihan', saldo: 48500000, alokasiPersen: 35, color: '#10b981' },
  { id: 2, nama: 'Kas Dakwah & Pengajian', saldo: 24750000, alokasiPersen: 30, color: '#3b82f6' },
  { id: 3, nama: 'Kas Pembangunan & Infrastruktur', saldo: 82300000, alokasiPersen: 20, color: '#f59e0b' },
  { id: 4, nama: 'Kas Sosial & Santunan Yatim', saldo: 31200000, alokasiPersen: 15, color: '#8b5cf6' },
];

export const INITIAL_TRANSAKSI: Transaksi[] = [
  {
    id: 101,
    tipe: 'IN',
    nominal: 12500000,
    keterangan: 'Infaq Tromol Shalat Jumat Pekan ke-3 September',
    tanggal: '2026-09-19T13:30:00',
    userId: 3,
    userNama: 'Fian Tampan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 102,
    tipe: 'IN',
    nominal: 5000000,
    keterangan: 'Donasi Hamba Allah untuk Renovasi Tempat Wudhu Akhwat',
    tanggal: '2026-09-18T10:15:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 3,
    kategoriNama: 'Kas Pembangunan & Infrastruktur',
  },
  {
    id: 103,
    tipe: 'OUT',
    nominal: 3450000,
    keterangan: 'Pembayaran Tagihan Listrik PLN & Air PDAM September',
    tanggal: '2026-09-17T09:00:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 104,
    tipe: 'OUT',
    nominal: 1500000,
    keterangan: 'Bisyarah / Kafalah Penceramah Tabligh Akbar Ahad Pagi',
    tanggal: '2026-09-15T08:30:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 2,
    kategoriNama: 'Kas Dakwah & Pengajian',
  },
  {
    id: 105,
    tipe: 'IN',
    nominal: 7800000,
    keterangan: 'Infaq QRIS Digital Jamaah via Bank Syariah',
    tanggal: '2026-09-14T16:00:00',
    userId: 1,
    userNama: 'H. Ahmad Dahlan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 106,
    tipe: 'OUT',
    nominal: 4200000,
    keterangan: 'Santunan Bulanan 14 Anak Yatim Binaan DKM',
    tanggal: '2026-09-10T14:00:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 4,
    kategoriNama: 'Kas Sosial & Santunan Yatim',
  },
  {
    id: 107,
    tipe: 'IN',
    nominal: 11200000,
    keterangan: 'Infaq Tromol Shalat Jumat Pekan ke-2 September',
    tanggal: '2026-09-12T13:30:00',
    userId: 3,
    userNama: 'Fian Tampan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 108,
    tipe: 'OUT',
    nominal: 2800000,
    keterangan: 'Pengadaan Karpet Shaf Tambahan Ruang Utama',
    tanggal: '2026-09-08T11:20:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 3,
    kategoriNama: 'Kas Pembangunan & Infrastruktur',
  },
  {
    id: 109,
    tipe: 'IN',
    nominal: 10500000,
    keterangan: 'Infaq Tromol Shalat Jumat Pekan ke-1 September',
    tanggal: '2026-09-05T13:30:00',
    userId: 3,
    userNama: 'Fian Tampan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 110,
    tipe: 'OUT',
    nominal: 1200000,
    keterangan: 'Belanja Alat Kebersihan, Sabun Cuci & Pewangi Karpet',
    tanggal: '2026-09-03T10:00:00',
    userId: 3,
    userNama: 'Fian Tampan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  // Data Bulan Lalu (Agustus 2026) untuk pembanding tren
  {
    id: 91,
    tipe: 'IN',
    nominal: 39500000,
    keterangan: 'Total Rekapitulasi Infaq Masuk Bulan Agustus 2026',
    tanggal: '2026-08-31T23:59:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
  {
    id: 92,
    tipe: 'OUT',
    nominal: 15400000,
    keterangan: 'Total Rekapitulasi Pengeluaran Operasional Agustus 2026',
    tanggal: '2026-08-31T23:59:00',
    userId: 2,
    userNama: 'Ustadz Ridwan',
    kategoriId: 1,
    kategoriNama: 'Kas Operasional & Kebersihan',
  },
];

export const INITIAL_FASILITAS: Fasilitas[] = [
  {
    id: 1,
    nama: 'Aula Utama Serbaguna (Lantai 2)',
    deskripsi: 'Dilengkapi AC Central, Sound System Premium, Panggung & 250 Kursi Futura.',
    kapasitas: '300 Jamaah',
    biayaInfaq: 1500000,
  },
  {
    id: 2,
    nama: 'Ruang Rapat & Majelis Taklim (Lantai 1)',
    deskripsi: 'Ruang ber-AC dengan Meja Konferensi, Proyektor Smart TV, Sound rapat.',
    kapasitas: '60 Jamaah',
    biayaInfaq: 500000,
  },
  {
    id: 3,
    nama: 'Tenda Sarnafil & Kursi Lipat Inventaris DKM',
    deskripsi: 'Paket 2 Unit Tenda 4x4m + 100 Kursi Lipat Chitose untuk kegiatan warga.',
    kapasitas: 'Outdoor',
    biayaInfaq: 750000,
  },
];

export const INITIAL_RESERVASI: Reservasi[] = [
  {
    id: 201,
    namaPemohon: 'Bpk. Hendra Gunawan',
    kontak: '081289123456',
    tujuanAcara: 'Akad Nikah & Walimah Putri Pertama',
    waktuMulai: '2026-09-26T08:00',
    waktuSelesai: '2026-09-26T14:00',
    status: 'APPROVED',
    fasilitasId: 1,
    fasilitasNama: 'Aula Utama Serbaguna (Lantai 2)',
    catatanAdmin: 'Wajib menjaga kebersihan dan selesai sebelum Ashar. Infaq kebersihan lunas.',
    createdAt: '2026-09-12T10:00:00',
  },
  {
    id: 202,
    namaPemohon: 'Ketua RW 08 (Bpk. M. Syafei)',
    kontak: '085712349988',
    tujuanAcara: 'Rapat Pleno Koordinasi Keamanan & Kebersihan Lingkungan',
    waktuMulai: '2026-09-27T19:30',
    waktuSelesai: '2026-09-27T22:00',
    status: 'APPROVED',
    fasilitasId: 2,
    fasilitasNama: 'Ruang Rapat & Majelis Taklim (Lantai 1)',
    catatanAdmin: 'Penggunaan gratis untuk kegiatan kemasyarakatan warga sekitar masjid.',
    createdAt: '2026-09-15T14:20:00',
  },
  {
    id: 203,
    namaPemohon: 'Ibu Rahmawati Nur',
    kontak: '081399887766',
    tujuanAcara: 'Kajian Muslimah & Santunan Yatim Dhuafa',
    waktuMulai: '2026-09-28T09:00',
    waktuSelesai: '2026-09-28T12:00',
    status: 'PENDING',
    fasilitasId: 1,
    fasilitasNama: 'Aula Utama Serbaguna (Lantai 2)',
    catatanAdmin: '',
    createdAt: '2026-09-20T08:15:00',
  },
  {
    id: 204,
    namaPemohon: 'Sdr. Dimas Prasetyo',
    kontak: '087811223344',
    tujuanAcara: 'Bazar Komunitas Musik Akustik Pemuda',
    waktuMulai: '2026-09-29T15:00',
    waktuSelesai: '2026-09-29T21:00',
    status: 'REJECTED',
    fasilitasId: 1,
    fasilitasNama: 'Aula Utama Serbaguna (Lantai 2)',
    catatanAdmin: 'Mohon maaf, format acara tidak sesuai dengan pedoman penggunaan fasilitas masjid.',
    createdAt: '2026-09-18T11:00:00',
  },
];

export const INITIAL_MUSTAHIQ: Mustahiq[] = [
  {
    id: 1,
    nama: 'Pak Salim (62 th)',
    alamat: 'Jl. Melati No. 12, RT 01/RW 03',
    kategori: 'FAKIR',
    status: true,
    jumlahTanggungan: 3,
    statusDistribusi: 'SUDAH',
  },
  {
    id: 2,
    nama: 'Ibu Warsiti (Janda Lansia)',
    alamat: 'Gang Kamboja II No. 5, RT 02/RW 03',
    kategori: 'MISKIN',
    status: true,
    jumlahTanggungan: 1,
    statusDistribusi: 'BELUM',
  },
  {
    id: 3,
    nama: 'Kang Asep (Buruh Harian)',
    alamat: 'Jl. Kenanga Timur, RT 04/RW 04',
    kategori: 'MISKIN',
    status: true,
    jumlahTanggungan: 4,
    statusDistribusi: 'BELUM',
  },
  {
    id: 4,
    nama: 'Ustadz Jaelani (Guru Ngaji Kampung)',
    alamat: 'Belakang Masjid Blok B, RT 03/RW 03',
    kategori: 'FISABILILLAH',
    status: true,
    jumlahTanggungan: 5,
    statusDistribusi: 'SUDAH',
  },
  {
    id: 5,
    nama: 'Sdr. Michael Abdullah (Mualaf Baru)',
    alamat: 'Perum Flamboyan Asri B-12',
    kategori: 'MUALAF',
    status: true,
    jumlahTanggungan: 1,
    statusDistribusi: 'BELUM',
  },
  {
    id: 6,
    nama: 'Pak Kosasih (Penggali Kubur)',
    alamat: 'Kp. Dukuh RT 05/RW 02',
    kategori: 'FAKIR',
    status: true,
    jumlahTanggungan: 2,
    statusDistribusi: 'BELUM',
  },
];

export const INITIAL_HEWAN_QURBAN: HewanQurban[] = [
  {
    id: 1,
    kodeHewan: 'SAPI-01 (Limousin Super)',
    tipeHewan: 'SAPI',
    hargaBeli: 24500000,
    slotMaks: 7,
    shohibul: [
      { id: 1, nama: 'Bpk. H. Bambang Soetrisno', atasNama: 'H. Bambang bin Soetrisno & Keluarga', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-01' },
      { id: 2, nama: 'Ibu Hj. Siti Nurjanah', atasNama: 'Hj. Siti binti Abdullah', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-02' },
      { id: 3, nama: 'Bpk. Dr. Faisal Akbar', atasNama: 'Faisal Akbar bin Syamsuddin', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-03' },
      { id: 4, nama: 'Ibu Ratna Dewi', atasNama: 'Ratna Dewi binti Wardoyo', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-05' },
      { id: 5, nama: 'Bpk. Kurniawan Eko', atasNama: 'Kurniawan Eko bin Subarjo', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-07' },
      { id: 6, nama: 'Bpk. Agus Salim', atasNama: 'Agus Salim bin Rahmat', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-08' },
      { id: 7, nama: 'Ibu Mega Kartika', atasNama: 'Mega Kartika binti Suwandi', bayarLunas: true, hewanId: 1, tanggalDaftar: '2026-09-10' },
    ],
  },
  {
    id: 2,
    kodeHewan: 'SAPI-02 (Simental Jawa)',
    tipeHewan: 'SAPI',
    hargaBeli: 22400000,
    slotMaks: 7,
    shohibul: [
      { id: 8, nama: 'Bpk. Teguh Wibowo', atasNama: 'Teguh Wibowo & Keluarga', bayarLunas: true, hewanId: 2, tanggalDaftar: '2026-09-12' },
      { id: 9, nama: 'Ibu Nurhayati', atasNama: 'Nurhayati binti Hasan', bayarLunas: true, hewanId: 2, tanggalDaftar: '2026-09-14' },
      { id: 10, nama: 'Bpk. Irfan Maulana', atasNama: 'Irfan Maulana bin Iskandar', bayarLunas: false, hewanId: 2, tanggalDaftar: '2026-09-18' },
      { id: 11, nama: 'Ibu Dian Safitri', atasNama: 'Almh. Ibunda Mariam', bayarLunas: true, hewanId: 2, tanggalDaftar: '2026-09-19' },
    ],
  },
  {
    id: 3,
    kodeHewan: 'KAMBING-01 (Etawa Premium)',
    tipeHewan: 'KAMBING',
    hargaBeli: 3800000,
    slotMaks: 1,
    shohibul: [
      { id: 12, nama: 'Bpk. H. Rasyid Ridho', atasNama: 'H. Rasyid Ridho bin Mansur', bayarLunas: true, hewanId: 3, tanggalDaftar: '2026-09-15' },
    ],
  },
];

export const INITIAL_PEGAWAI: Pegawai[] = [
  {
    id: 1,
    nama: 'Ustadz M. Syakir, Lc.',
    jabatan: 'IMAM',
    gajiPokok: 3500000,
    tunjanganHadir: 50000,
    rekening: 'BSI 7149021882',
    noHp: '081234567890',
  },
  {
    id: 2,
    nama: 'Kang Bilal Ar-Rafi',
    jabatan: 'MUADZIN',
    gajiPokok: 2400000,
    tunjanganHadir: 30000,
    rekening: 'BSI 7188992211',
    noHp: '081399001122',
  },
  {
    id: 3,
    nama: 'Pak Sukiman',
    jabatan: 'MARBOT',
    gajiPokok: 2200000,
    tunjanganHadir: 25000,
    rekening: 'BRI 012301048821501',
    noHp: '085211993344',
  },
  {
    id: 4,
    nama: 'Ustadzah Halimah, S.Pd.I',
    jabatan: 'GURU_TPA',
    gajiPokok: 1800000,
    tunjanganHadir: 35000,
    rekening: 'Bank Mandiri 1330018899221',
    noHp: '081988223311',
  },
  {
    id: 5,
    nama: 'Pak Slamet Riyadi',
    jabatan: 'SATPAM',
    gajiPokok: 2200000,
    tunjanganHadir: 25000,
    rekening: 'BCA 8820199201',
    noHp: '087711224455',
  },
];

export const INITIAL_ABSENSI: Absensi[] = [
  { id: 1, tanggal: '2026-09-21', waktuSalat: 'SUBUH', status: 'HADIR', pegawaiId: 1, pegawaiNama: 'Ustadz M. Syakir, Lc.' },
  { id: 2, tanggal: '2026-09-21', waktuSalat: 'SUBUH', status: 'HADIR', pegawaiId: 2, pegawaiNama: 'Kang Bilal Ar-Rafi' },
  { id: 3, tanggal: '2026-09-21', waktuSalat: 'SUBUH', status: 'HADIR', pegawaiId: 3, pegawaiNama: 'Pak Sukiman' },
  { id: 4, tanggal: '2026-09-21', waktuSalat: 'DZUHUR', status: 'HADIR', pegawaiId: 1, pegawaiNama: 'Ustadz M. Syakir, Lc.' },
  { id: 5, tanggal: '2026-09-21', waktuSalat: 'DZUHUR', status: 'HADIR', pegawaiId: 2, pegawaiNama: 'Kang Bilal Ar-Rafi' },
  { id: 6, tanggal: '2026-09-21', waktuSalat: 'ASHAR', status: 'HADIR', pegawaiId: 1, pegawaiNama: 'Ustadz M. Syakir, Lc.' },
  { id: 7, tanggal: '2026-09-21', waktuSalat: 'ASHAR', status: 'HADIR', pegawaiId: 2, pegawaiNama: 'Kang Bilal Ar-Rafi' },
];

export const INITIAL_SLIP_GAJI: SlipGaji[] = [
  {
    id: 1,
    bulan: 'September 2026',
    gajiPokok: 3500000,
    tunjangan: 1250000,
    potongan: 0,
    nominal: 4750000,
    status: 'PENDING',
    pegawaiId: 1,
    pegawaiNama: 'Ustadz M. Syakir, Lc.',
    pegawaiJabatan: 'IMAM',
    createdAt: '2026-09-21T08:00:00',
  },
  {
    id: 2,
    bulan: 'September 2026',
    gajiPokok: 2400000,
    tunjangan: 750000,
    potongan: 60000, // potong 2x alpa
    nominal: 3090000,
    status: 'PENDING',
    pegawaiId: 2,
    pegawaiNama: 'Kang Bilal Ar-Rafi',
    pegawaiJabatan: 'MUADZIN',
    createdAt: '2026-09-21T08:00:00',
  },
  {
    id: 3,
    bulan: 'September 2026',
    gajiPokok: 2200000,
    tunjangan: 625000,
    potongan: 0,
    nominal: 2825000,
    status: 'PENDING',
    pegawaiId: 3,
    pegawaiNama: 'Pak Sukiman',
    pegawaiJabatan: 'MARBOT',
    createdAt: '2026-09-21T08:00:00',
  },
  {
    id: 4,
    bulan: 'Agustus 2026',
    gajiPokok: 3500000,
    tunjangan: 1300000,
    potongan: 0,
    nominal: 4800000,
    status: 'PAID',
    pegawaiId: 1,
    pegawaiNama: 'Ustadz M. Syakir, Lc.',
    pegawaiJabatan: 'IMAM',
    createdAt: '2026-08-31T10:00:00',
  },
];

export const INITIAL_ZAKAT_TRX: ZakatFitrahTrx[] = [
  {
    id: 1,
    namaMuzakki: 'H. Suherman & Keluarga',
    kontak: '081299887766',
    jenisZakat: 'FITRAH_BERAS',
    jumlahJiwa: 5,
    jumlahBerasKg: 12.5,
    tanggal: '2026-09-20T10:30:00',
    noKupon: 'ZKT-2026-001',
  },
  {
    id: 2,
    namaMuzakki: 'Bpk. Ridho Pratama',
    kontak: '085711223344',
    jenisZakat: 'FITRAH_UANG',
    jumlahJiwa: 4,
    nominalRp: 200000, // 4 x Rp 50.000
    tanggal: '2026-09-20T14:15:00',
    noKupon: 'ZKT-2026-002',
  },
  {
    id: 3,
    namaMuzakki: 'Ibu Hj. Mariam',
    kontak: '081344556677',
    jenisZakat: 'ZAKAT_MAAL',
    jumlahJiwa: 1,
    nominalRp: 4500000,
    tanggal: '2026-09-21T09:00:00',
    noKupon: 'ZKT-2026-003',
  },
];

export const INITIAL_WARGA: Warga[] = [
  {
    id: 1,
    nama: 'Bpk. H. Bambang Soetrisno',
    nik: '3275010203800001',
    noHp: '081299887766',
    alamat: 'Jl. Maskoki 1 No. 14, RT 02/RW 08',
    rt: '02',
    rw: '08',
    gender: 'IKHWAN',
    kategoriUmur: 'DEWASA',
    umur: 48,
    isMustahik: false,
    statusKeluarga: 'KEPALA_KELUARGA',
    pekerjaan: 'Wiraswasta',
    tanggalDaftar: '2026-01-10',
  },
  {
    id: 2,
    nama: 'Ibu Hj. Siti Nurjanah',
    nik: '3275014503820002',
    noHp: '081388776655',
    alamat: 'Jl. Maskoki 1 No. 14, RT 02/RW 08',
    rt: '02',
    rw: '08',
    gender: 'AKHWAT',
    kategoriUmur: 'DEWASA',
    umur: 44,
    isMustahik: false,
    statusKeluarga: 'ISTRI',
    pekerjaan: 'Ibu Rumah Tangga',
    tanggalDaftar: '2026-01-10',
  },
  {
    id: 3,
    nama: 'Pak Salim',
    nik: '3275010505640003',
    noHp: '085712349911',
    alamat: 'Jl. Maskoki Raya Gang Melati No. 12, RT 01/RW 08',
    rt: '01',
    rw: '08',
    gender: 'IKHWAN',
    kategoriUmur: 'LANSIA',
    umur: 62,
    isMustahik: true,
    statusKeluarga: 'KEPALA_KELUARGA',
    pekerjaan: 'Buruh Serabutan',
    tanggalDaftar: '2026-02-14',
  },
  {
    id: 4,
    nama: 'Ibu Warsiti',
    nik: '3275014806580004',
    noHp: '087812993344',
    alamat: 'Gang Kamboja II No. 5, RT 02/RW 08',
    rt: '02',
    rw: '08',
    gender: 'AKHWAT',
    kategoriUmur: 'LANSIA',
    umur: 68,
    isMustahik: true,
    statusKeluarga: 'KEPALA_KELUARGA',
    pekerjaan: 'Tidak Bekerja (Janda Lansia)',
    tanggalDaftar: '2026-02-20',
  },
  {
    id: 5,
    nama: 'Ahmad Fauzi',
    nik: '3275011208070005',
    noHp: '089611223344',
    alamat: 'Jl. Maskoki 3 No. 8, RT 03/RW 08',
    rt: '03',
    rw: '08',
    gender: 'IKHWAN',
    kategoriUmur: 'REMAJA',
    umur: 19,
    isMustahik: false,
    statusKeluarga: 'ANAK',
    pekerjaan: 'Mahasiswa / Remaja Masjid',
    tanggalDaftar: '2026-03-01',
  },
  {
    id: 6,
    nama: 'Fatimah Az-Zahra',
    nik: '3275015509150006',
    noHp: '081277665544',
    alamat: 'Jl. Maskoki 3 No. 8, RT 03/RW 08',
    rt: '03',
    rw: '08',
    gender: 'AKHWAT',
    kategoriUmur: 'ANAK',
    umur: 11,
    isMustahik: false,
    statusKeluarga: 'ANAK',
    pekerjaan: 'Santri TPA Al-Muhajirin',
    tanggalDaftar: '2026-03-01',
  },
  {
    id: 7,
    nama: 'Kang Asep Supriatna',
    nik: '3275011010830007',
    noHp: '085299881122',
    alamat: 'Jl. Maskoki 4 No. 22, RT 04/RW 08',
    rt: '04',
    rw: '08',
    gender: 'IKHWAN',
    kategoriUmur: 'DEWASA',
    umur: 43,
    isMustahik: true,
    statusKeluarga: 'KEPALA_KELUARGA',
    pekerjaan: 'Buruh Bangunan',
    tanggalDaftar: '2026-03-15',
  },
  {
    id: 8,
    nama: 'Ibu Ratna Sari',
    nik: '3275015011880008',
    noHp: '081311002233',
    alamat: 'Jl. Maskoki 2 No. 19, RT 02/RW 08',
    rt: '02',
    rw: '08',
    gender: 'AKHWAT',
    kategoriUmur: 'DEWASA',
    umur: 38,
    isMustahik: false,
    statusKeluarga: 'ISTRI',
    pekerjaan: 'Guru TK / Majelis Taklim',
    tanggalDaftar: '2026-04-02',
  },
];

export const INITIAL_PROFIL_LEMBAGA: ProfilLembaga = {
  nama: 'AL-Muhajirin',
  yayasan: 'Yayasan Kemakmuran Umat Kayuringin Jaya',
  periode: 'Periode 2024 - 2028',
  alamat: 'Jl. Maskoki Raya Perumnas 2 Kayuringin Jaya Bekasi',
  telepon: '0812-9876-5432',
  email: 'dkm.almuhajirin.bekasi@gmail.com',
  deskripsi: 'Dewan Kemakmuran Masjid (DKM) yang berkomitmen membina umat melalui dakwah, pendidikan, sosial, dan transparansi keuangan berbasis digital.',
  logoUrl: '/logo.png',
};

export const INITIAL_PENGURUS_LEMBAGA: PengurusLembaga[] = [
  { id: 1, role: 'Ketua DKM', nama: 'H. Ahmad Dahlan', noHp: '081211223344', icon: '👤' },
  { id: 2, role: 'Wakil Ketua', nama: 'H. Bambang Soetrisno', noHp: '081322334455', icon: '👤' },
  { id: 3, role: 'Sekretaris', nama: 'Fian Tampan (Piket)', noHp: '085733445566', icon: '📝' },
  { id: 4, role: 'Bendahara Umum', nama: 'Ustadz Ridwan, S.E', noHp: '081844556677', icon: '💰' },
  { id: 5, role: 'Ketua Bidang ZISWAF', nama: 'H. Suherman', noHp: '085255667788', icon: '🤝' },
  { id: 6, role: 'Imam Rawatib', nama: 'Ustadz M. Syakir, Lc.', noHp: '081366778899', icon: '🕌' },
];

export const INITIAL_REKENING_LEMBAGA: RekeningLembaga[] = [
  {
    id: 1,
    bank: 'BANK SYARIAH INDONESIA (BSI)',
    noRekening: '714-902-1882',
    atasNama: 'DKM AL-MUHAJIRIN BEKASI',
  },
  {
    id: 2,
    bank: 'BANK MUAMALAT',
    noRekening: '348-001-9281',
    atasNama: 'YAYASAN AL-MUHAJIRIN BEKASI',
  },
];

export const INITIAL_KEGIATAN: Kegiatan[] = [
  {
    id: 1,
    judul: 'Kajian Subuh Berjamaah & Sarapan Bersama',
    narasumber: 'Ustadz M. Syakir, Lc.',
    waktu: 'Setiap Ahad Pagi, Ba\'da Subuh',
    lokasi: 'Ruang Utama AL-Muhajirin',
    kategori: 'RUTIN MINGGUAN',
    deskripsi: 'Kajian kitab Riyadhus Shalihin dilanjutkan sarapan bersama jamaah.',
    kontakPIC: '0812-1122-3344',
  },
  {
    id: 2,
    judul: 'Majelis Taklim Muslimah & Tahsin Al-Qur\'an',
    narasumber: 'Ustadzah Hj. Faridah',
    waktu: 'Setiap Selasa, 09.00 - 11.30 WIB',
    lokasi: 'Aula Serbaguna Lantai 2',
    kategori: 'MUSLIMAH',
    deskripsi: 'Bimbingan tahsin makhorijul huruf dan fikih wanita.',
    kontakPIC: '0813-2233-4455',
  },
  {
    id: 3,
    judul: 'Pelatihan Qiro\'ah & Hadrah Remaja Masjid',
    narasumber: 'Tim Remaja DKM',
    waktu: 'Setiap Sabtu Malam, Ba\'da Isya',
    lokasi: 'Serambi Timur AL-Muhajirin',
    kategori: 'REMAJA',
    deskripsi: 'Latihan seni hadrah banjari dan qiroah murattal santri remaja.',
    kontakPIC: '0857-3344-5566',
  },
  {
    id: 4,
    judul: 'Khotbah & Shalat Jumat Berjamaah',
    narasumber: 'Habib Ali Al-Kaff',
    waktu: 'Setiap Jumat, 11.45 WIB',
    lokasi: 'Ruang Shalat Utama',
    kategori: 'SHALAT JUMAT',
    deskripsi: 'Shalat Jumat berjamaah dengan khutbah tematik seputar ukhuwah islamiyah.',
    kontakPIC: '0818-4455-6677',
  },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: 1, nama: 'Genset Silent 5000 Watt', jumlah: '1 Unit', kondisi: 'BAIK', lokasi: 'Gudang Belakang', kategori: 'Elektronik & Kelistrikan' },
  { id: 2, nama: 'Karpet Shaf Turkey Tebal 14mm', jumlah: '18 Gulung', kondisi: 'BAIK', lokasi: 'Ruang Utama', kategori: 'Ibadah & Karpet' },
  { id: 3, nama: 'Sound System Wireless Mixer 16 Ch', jumlah: '1 Set', kondisi: 'BAIK', lokasi: 'Ruang Sound', kategori: 'Elektronik & Sound' },
  { id: 4, nama: 'Microphone Shure Beta 58A', jumlah: '6 Pcs', kondisi: 'BAIK', lokasi: 'Mimbar & Muadzin', kategori: 'Elektronik & Sound' },
  { id: 5, nama: 'Tenda Sarnafil 4x4 Meter', jumlah: '2 Set', kondisi: 'BAIK', lokasi: 'Gudang Tenda', kategori: 'Tenda & Outdoor' },
  { id: 6, nama: 'Kursi Lipat Futura', jumlah: '150 Unit', kondisi: 'BAIK', lokasi: 'Aula Lantai 2', kategori: 'Perlengkapan & Furnitur' },
  { id: 7, nama: 'Keranda Jenazah & Kain Penutup', jumlah: '1 Set', kondisi: 'BAIK', lokasi: 'Ruang Jenazah', kategori: 'Sosial & Fardhu Kifayah' },
];




